### ISSUE TITLE
Explain steps a bit better?

### ISSUE THREAD

**Issue by ronag** [redux-effects/redux-effects#4]
We are a bit confused in regards to steps. I think we are missing a descriptive example?

**Comment by ashaffer** [comment]
Ah, sorry.  Steps is a linearly executed chain of handlers.  Like this:

``` javascript
{
  type: 'FETCH',
  payload: {
    url: '/user',
    params: {method: 'GET'}
  },
  meta: {
    steps: [[user => userDidResolve(user), err => userDidError(err)]]
  }
}
```

You can also chain many steps, e.g.

``` javascript
{
  type: 'FETCH',
  payload: {
    url: '/user',
    params: {method: 'GET'}
  },
  meta: {
    steps: [
      [user => {type: 'FETCH', payload: {url: '/notification/' + user.id}}],
      [notifications => notificationsDidResolve(notifications)]
    ]
  }
}
```

Each array in `steps` is roughly equivalent to a `.then` in a promise chain.  It's easier to think about if you using something like [bind-effect](https://github.com/redux-effects/bind-effect).

The value returned by your step functions are dispatched back into redux.  So you can dispatch another effect action, or at the end of your chain, you can dispatch a plain action that does something to state.

The thing that executes steps looks like this:

``` javascript
steps.reduce(function (promise, step) {
  return promise.then(
    function (value) {
      dispatch(step[0](value))
    },
    function (error) {
      dispatch(step[1](error))
    }
  }
}, promise)
```

Where the initial value of `promise` is the promise returned by your initial effect.  All this is is a way of declaratively specifying the computation tree you want to execute, and then letting your redux middleware actually execute it for you.

Does that make sense?

EDIT: So using some helper libraries you might write this (an example from [declarative-fetch](https://github.com/redux-effects/declarative-fetch)):

```
import bind from 'bind-effect'
import fetch from 'declarative-fetch'
import {createAction} from 'redux-actions'

function createUser (user) {
  return bind(fetch('/user', {
    method: 'POST',
    body: user
  }), user => userCreated)
}

const userCreated = createAction('USER_CREATED')
```

But this is just syntactic sugar, for this:

``` javascript
function createUser (user) {
  return {
    payload: {
      type: 'FETCH',
      params: {
        method: 'POST', 
        body: user
      }
    }
    steps: [
      [response => {type: 'USER_CREATED', payload: response}]
    ]
  }  
}
```

**Comment by ronag** [comment]
Ah yes. Thank you.
