### ISSUE TITLE
0.4.1 on npm is not transpiled to es5

### ISSUE THREAD

**Issue by mattwigway** [redux-effects/redux-effects#7]
`redux-effects` 0.4.1 was just pushed to npm, and it seems the code that was pushed is written in ES6 and not transpiled. Looking at the `package.json` it appears this is unintentional as babel is still included.

**Comment by ashaffer** [comment]
Oh man. Sorry, apparently my babelrc has been spelled 'bablerc' this entire time, and it hadn't mattered for babel5. Fixed & published.

**Comment by mattwigway** [comment]
Thanks!
